# https://github.com/shuttle-hq/deploy-action#readme
name: Shuttle Deploy

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          working-directory: "apps/api"
          name: "moodi-api"
